services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - '3000:${PORT}'
    depends_on:
      - postgres
      - s3ninja
    networks:
      - bonusx-network

  postgres:
    hostname: database.local
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bonusx-network

  s3ninja:
    hostname: storage.local
    image: scireum/s3-ninja:latest
    ports:
      - '9000:9000'
    volumes:
      - ./docker/storage_data:/home/sirius/data
    networks:
      - bonusx-network

volumes:
  postgres_data:
  s3ninja_data:

networks:
  bonusx-network:
    driver: bridge
